module.exports = [
    { "id": 1, "name": "Ms. Supriya Nadiger" },
    { "id": 2, "name": "Ms. Supritha M Shetty" },
    { "id": 3, "name": "Mr. Amruth Gadag" },
    { "id": 4, "name": "Mr. Shankar Biradar" },
    { "id": 5, "name": "Ms. Ashwini Dasare" },
    { "id": 6, "name": "Ms. Namita Gokavi" },
    { "id": 7, "name": "Mr. Pradyoth Hegde" },
    { "id": 8, "name": "Mr. Prashant Bannulmath" },
    { "id": 9, "name": "Mr. Shrirang Pujari" },
    { "id": 10, "name": "Mr. Swapnil Sontakke" },
    { "id": 11, "name": "Ms. Shraddha Revankar" },
    { "id": 12, "name": "Ms. Gautami Naik" },
    { "id": 13, "name": "Ms. Ashwini Chikkenakoppa" },
    { "id": 14, "name": "Mr. Vinod Konnur" },
    { "id": 15, "name": "Mr. Santosh G Kondaguli" },
    { "id": 16, "name": "Mrs. Vani Yelamali" },
    { "id": 17, "name": "Mr. RAKSHITH B" },
    { "id": 18, "name": "Mr. Sandeep Singh" },
    { "id": 19, "name": "Brindashree B V" },
    { "id": 20, "name": "Mr. Anil Mallappa Kabbur" },
    { "id": 21, "name": "Mrs. Madhu Asundi" },
    { "id": 22, "name": "Mr. ADITHYA D A" },
    { "id": 23, "name": "Mrs. Chandrika Bhosge" },
    { "id": 24, "name": "Mrs. Sneha Shetty R" },
    { "id": 25, "name": "Mrs. Smitha K" },
    { "id": 26, "name": "Mr. Karusala Deepak Chowdary" },
    { "id": 27, "name": "Meghana Pujar" },
    { "id": 28, "name": "Olivia Gogoi" },
    { "id": 29, "name": "Chunduru Anilkumar" },
    { "id": 30, "name": "Sabyasachi Ghosal" },
    { "id": 31, "name": "Vimal N B" },
    { "id": 32, "name": "Mamatha E" },
    { "id": 33, "name": "Shrinivas Neeralakeri" },
    { "id": 34, "name": "Sahana Punagin" },
    { "id": 35, "name": "Mrs. Jyoti Gadad" },
    { "id": 36, "name": "PALSHINI B LIMBANI" },
    { "id": 37, "name": "Ms. Priyanka M Jakali" },
    { "id": 38, "name": "Ms. Banasmita Patra" }
  ];